FROM tomcat
#Descargar de internet una libreria
ADD https://jdbc.postgresql.org/download/postgresql-42.3.3.jar /usr/local/tomcat/lib/
##Copiar archivo local
COPY demoHa.war /usr/local/tomcat/webapps/
